### ISSUE TITLE
ERROR:root:'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by citizenkahn** [cevoaustralia/aws-google-auth#167] opened 2020-02-27 19:59 UTC
It seems like a variant of #52 is back or at least for several of us.  We see this intermittently and it seems to happen on multiple machine in multiple network environments (home, office, vpn / no vpn).  Usually we see 1-3 failure before a success. 

# Environment
 - MacOS: 10.15.3 (19.3.0 Darwin Kernel Version 19.3.0)
 - Python 3.7.6
```
aws-google-auth    0.0.33
beautifulsoup4     4.8.1
boto3              1.10.32
botocore           1.13.32
cached-property    1.5.1
certifi            2019.11.28
chardet            3.0.4
configparser       4.0.2
docker-compose     1.8.0
docker-py          1.10.6
docker-pycreds     0.4.0
dockerpty          0.4.1
docopt             0.6.2
docutils           0.15.2
idna               2.8
importlib-metadata 1.1.0
jmespath           0.9.4
jsonschema         2.6.0
keyring            19.3.0
keyrings.alt       3.2.0
lxml               4.4.2
more-itertools     8.0.0
Pillow             6.2.1
pip                19.3.1
python-dateutil    2.8.0
pytz               2019.3
PyYAML             3.13
requests           2.7.0
s3transfer         0.2.1
setuptools         42.0.2
six                1.13.0
soupsieve          1.9.5
tabulate           0.8.6
texttable          0.8.8
tzlocal            2.0.0
urllib3            1.25.7
websocket-client   0.57.0
wheel              0.33.6
zipp               0.6.0
```

# Error
```
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aws_google_auth/__init__.py", line 73, in cli
    process_auth(args, config)
  File "/usr/local/lib/python3.7/site-packages/aws_google_auth/__init__.py", line 218, in process_auth
    google_client.do_login()
  File "/usr/local/lib/python3.7/site-packages/aws_google_auth/google.py", line 228, in do_login
    'name': 'ProfileInformation'
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by SpamapS** [comment] 2020-02-27 20:06
Confirmed, this is happening to folks in my org too.

**Comment by SpamapS** [comment] 2020-02-27 20:12
Just worked for me after 15 retries.

Maybe it's just a different version of the challenge page.

**Comment by seanlutner** [comment] 2020-02-27 20:14
Definitely have been seeing this error frequently lately. Sometimes it works 1 second later and sometimes it fails for a few hours.

**Comment by stevemac007** [comment] 2020-02-27 21:31
Looks like google is making changes to the login flow... again..  Will need to dig into more reverse engineering to understand the impact of the change.

**Comment by barryoneill** [comment] 2020-02-27 21:57
duplicate of https://github.com/cevoaustralia/aws-google-auth/issues/164?

**Comment by citizenkahn** [comment] 2020-02-27 22:05
Yes a dupe.  Closed it. and I'll follow the other

**Closed** 2020-02-27 22:05 UTC
