### ISSUE TITLE
Intermittent 'ProfileInformation' error when logging in

### ISSUE THREAD

**Issue by celliott** [cevoaustralia/aws-google-auth#164] opened 2020-02-26 16:48 UTC
We have been successfully using `aws-google-auth` for months and it's been great. Starting Monday 2/24 we started Intermittently seeing the error below. I disabled 2fa on my GSuite account but it did not help. Is anyone else seeing this?

```
$ aws-google-auth -d 43200 -ak
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aws_google_auth/__init__.py", line 73, in cli
    process_auth(args, config)
  File "/usr/local/lib/python3.7/site-packages/aws_google_auth/__init__.py", line 218, in process_auth
    google_client.do_login()
  File "/usr/local/lib/python3.7/site-packages/aws_google_auth/google.py", line 228, in do_login
    'name': 'ProfileInformation'
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by ahilsend** [comment] 2020-02-26 20:27
We have been seeing it as well.

**Comment by jurgenweber** [comment] 2020-02-26 21:41
I just can not login right now.

**Comment by jurgenweber** [comment] 2020-02-26 21:45
ok, tried again 3 minutes later and it works, : \

**Comment by celliott** [comment] 2020-02-26 22:31
It has definitely been intermittent for us. Not all users are affected either. My gut is saying that it related to google bot protection for saml endpoints but I'm not sure how to debug and pinpoint yet. Any help would be appreciated. 

May be related to https://github.com/cevoaustralia/aws-google-auth/issues/160

**Comment by celliott** [comment] 2020-02-26 23:14
I printed out the `challenge_page` for both successful and unsuccessful attempts. Goggle is presenting different login pages. the question is why and how can I force the successful page? I can post the html bodies of each request if that is helpful. Just ask.

**_successful_**
<img width="532" alt="successful" src="https://user-images.githubusercontent.com/1156432/75396902-7ba02980-58aa-11ea-9f3e-827c1276df01.png">

**_unsuccessful_**
<img width="533" alt="unsuccessful" src="https://user-images.githubusercontent.com/1156432/75396918-82c73780-58aa-11ea-8136-1403fa500b89.png">

**Comment by JorgenSmith** [comment] 2020-02-27 01:07
Also experiencing this issue, on Windows Powershell 7.0.rc3 (PIP up to date, latest version of package according to `pip install aws-google-auth[u2f]`).  

Trying multiple times seems to finally resolve it.

Normally I use in app authentication which lives in Samsung Secure Folder, which requires additional phone app which sometimes times out. Nonetheless, if it doesn't work there it might then revert to SMS auth. 

My line numbers are only slightly different.

```C:\Users\Myself> aws-google-auth -k -p services
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Users\Myself\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\aws_google_auth\__init__.py", line 72, in cli
    process_auth(args, config)
  File "C:\Users\Myself\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\aws_google_auth\__init__.py", line 212, in process_auth
    google_client.do_login()
  File "C:\Users\Myself\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\aws_google_auth\google.py", line 225, in do_login
    'name': 'ProfileInformation'
AttributeError: 'NoneType' object has no attribute 'get'```

**Comment by roblugton** [comment] 2020-02-27 05:25
@JorgenSmith The problem comes from Google returning a different login page on some requests (as @celliott points out), the html source of which does not contain the information that `aws-google-auth` is looking for. 

We're taking a look at this at the moment.

**Comment by Gujarats** [comment] 2020-02-27 09:12
for the time being I used this extension on chrome to get the credentials https://chrome.google.com/webstore/detail/saml-to-aws-sts-keys-conv/ekniobabpcnfjgfbphhcolcinmnbehde/related

**Comment by jsafoodpanda** [comment] 2020-02-27 14:09
Did `--save-failure-html` worked for you in this case?


@jurgenweber Long time no see ;)

**Comment by williamcoates** [comment] 2020-02-27 15:08
`--save-failure-html` did not seem to work for me. 

The only way I can get around this issues it seems is by using a VPN service to switch to a different country which is peculiar! Then I get the regular 2FA prompt.

**Comment by jurgenweber** [comment] 2020-02-27 21:34
@jsafoodpanda G'Day mate. Indeed, long time.

Any closer to a resolution? Brute force logging isn't the best fun.

**Comment by Crevil** [comment] 2020-02-27 21:56
We are not seeing any successful attempts here. Anything we can do to help with this, please let me know. 🙏

**Comment by nonspecialist** [comment] 2020-02-27 21:59
I have a fix for this that I'm just validating now ... it's worked for me on the "new" page, I'm just cleaning it up before pushing

**Comment by nonspecialist** [comment] 2020-02-27 22:39
0.0.34 is live on pypi now and supports the new login form -- go give it a whirl

**Comment by celliott** [comment] 2020-02-27 22:47
@nonspecialist Thx for the quick fix! It is working reliably for me. Thx again. Will it also be pushed to homebrew?

**Comment by nonspecialist** [comment] 2020-02-27 22:51
@celliott I'll PR it into `homebrew-core` now

**Comment by celliott** [comment] 2020-02-27 23:04
@nonspecialist thank you again! so much appreciated.

**Comment by citizenkahn** [comment] 2020-02-27 23:05
Lightening fast turnaround.  Thanks

**Comment by jurgenweber** [comment] 2020-02-27 23:11
well done team!

**Comment by jurgenweber** [comment] 2020-02-27 23:14
https://github.com/Homebrew/homebrew-core/pull/50785 📦

**Comment by Akin2Silver** [comment] 2020-02-27 23:39
came for this exact issue, fix is working well for me. Thanks!

**Comment by nonspecialist** [comment] 2020-02-28 01:08
Thanks everyone for confirming, I'll close this now

**Closed by nonspecialist** 2020-02-28 01:08 UTC
Labels: bug

**Comment by aashari** [comment] 2020-02-28 04:31
Thanks @nonspecialist, it works for me 💯

**Comment by boshido** [comment] 2020-02-28 09:09
I still have problem after update
```
aws-google-auth -I xxxxxxxxx -S 9xxxxxx -d 43200 -u email@email.com -p default -a -l debug  --save-failure-html
INFO:root:aws_google_auth: SAML cache not found
Google Password:
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.google.com:443
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /o/saml2/initsso?idpid=xxxxxxxxx&spid=9xxxxxx&forceauthn=false HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /ServiceLogin?passive=1209600&continue=https://accounts.google.com/o/saml2/initsso?idpid%3Dxxxxxxxxx%26spid%3D9xxxxxx%26forceauthn%3Dfalse%26from_login%3D1%26as%3Dyj6qP2PkCSIUDToh4es-Xg&followup=https://accounts.google.com/o/saml2/initsso?idpid%3Dxxxxxxxxx%26spid%3D9xxxxxx%26forceauthn%3Dfalse%26from_login%3D1%26as%3Dyj6qP2PkCSIUDToh4es-Xg&ltmpl=popup&oauth=1&faa=1&sarp=1&scc=1 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /signin/v1/lookup HTTP/1.1" 302 552
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /signin/challenge/pwd/1?continue=https%3A%2F%2Faccounts.google.com%2Fo%2Fsaml2%2Finitsso%3Fidpid%3Dxxxxxxxxx%26spid%3D9xxxxxx%26forceauthn%3Dfalse%26from_login%3D1%26as%3Dyj6qP2PkCSIUDToh4es-Xg&sarp=1&scc=1&checkedDomains=youtube&pstMsg=0&oauth=1&TL=AKCKxpG1VqbfhRUYEpvzdRn74K7iuKNZsI7MfEcl5HTrlZKXeGlVQRU6YaBntygH HTTP/1.1" 200 None
INFO:root:Handling new-style login page
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /signin/challenge/pwd/1 HTTP/1.1" 200 None
ERROR:root:SAML lookup failed, storing failure page to 'saml.html' to assist with debugging.
Something went wrong - Could not find SAML response, check your credentials or use --save-failure-html to debug.
```

Error page
![Screen Shot 2563-02-28 at 16 06 22](https://user-images.githubusercontent.com/3489862/75526411-4fb8ab80-5a44-11ea-877f-e66a0d347c64.png)

**Comment by majeska** [comment] 2020-03-01 20:48
I'm still seeing this error on version 0.0.34

$ aws-google-auth -V
aws-google-auth 0.0.34

$ aws-google-auth 
Google Password: 
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/aws_google_auth/__init__.py", line 75, in cli
    process_auth(args, config)
  File "/Library/Python/3.7/site-packages/aws_google_auth/__init__.py", line 222, in process_auth
    google_client.do_login()
  File "/Library/Python/3.7/site-packages/aws_google_auth/google.py", line 235, in do_login
    passwd_challenge_url = 'https://accounts.google.com' + form.get('action')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by bhargavamin** [comment] 2020-08-13 08:13
I think the issue is back, many people from out organisation are also facing same issue again.

This time it’s mainly with the users trying to login using Captcha.

May be some thing changed Google side?

Error trace:
```
Captcha` (case insensitive): noustrumb
ERROR:root:'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aws_google_auth-0.0.36-py3.8.egg/aws_google_auth/__init__.py", line 78, in cli
    process_auth(args, config)
  File "/usr/lib/python3.8/site-packages/aws_google_auth-0.0.36-py3.8.egg/aws_google_auth/__init__.py", line 242, in process_auth
    google_client.do_login()
  File "/usr/lib/python3.8/site-packages/aws_google_auth-0.0.36-py3.8.egg/aws_google_auth/google.py", line 270, in do_login
    response_page = BeautifulSoup(sess.text, 'html.parser')
AttributeError: 'NoneType' object has no attribute 'text' 

```
Version 0.0.36
Python 3.8.3 and 3.8.0

Any ideas how to fix ?

Thanks in advance

**Comment by stephenrjohnson** [comment] 2020-11-10 09:26
I'm also seeing this issue 
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-google-auth/0.0.36_1/libexec/lib/python3.9/site-packages/aws_google_auth/__init__.py", line 78, in cli
    process_auth(args, config)
  File "/usr/local/Cellar/aws-google-auth/0.0.36_1/libexec/lib/python3.9/site-packages/aws_google_auth/__init__.py", line 242, in process_auth
    google_client.do_login()
  File "/usr/local/Cellar/aws-google-auth/0.0.36_1/libexec/lib/python3.9/site-packages/aws_google_auth/google.py", line 235, in do_login
    passwd_challenge_url = 'https://accounts.google.com' + form.get('action')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by dspv** [comment] 2021-02-07 10:37
Have the same problem now:
Happens when I allow sign-in on my smartphone

```
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aws_google_auth/__init__.py", line 79, in cli
    process_auth(args, config)
  File "/usr/local/lib/python3.9/site-packages/aws_google_auth/__init__.py", line 243, in process_auth
    google_client.do_login()
  File "/usr/local/lib/python3.9/site-packages/aws_google_auth/google.py", line 325, in do_login
    sess = self.handle_prompt(sess)
  File "/usr/local/lib/python3.9/site-packages/aws_google_auth/google.py", line 620, in handle_prompt
    response_page.find('input', {
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by myl82** [comment] 2022-04-13 07:05
Is there any solution, how to resolve this it?
The same issue:

**_aws-google-auth -I ******* -S xxxxxxx -d 28800 -p lmg -R ****** -uuser@email.com -k -l debug_**

`INFO:root:aws_google_auth: SAML cache not found
DEBUG:keyring.backend:Loading Gnome
DEBUG:keyring.backend:Loading Google
DEBUG:keyring.backend:Loading Windows (alt)
DEBUG:keyring.backend:Loading file
DEBUG:keyring.backend:Loading keyczar
DEBUG:keyring.backend:Loading multi
DEBUG:keyring.backend:Loading pyfs
DEBUG:keyring.backend:Loading KWallet
DEBUG:keyring.backend:Loading SecretService
DEBUG:keyring.backend:Loading Windows
DEBUG:keyring.backend:Loading chainer
DEBUG:keyring.backend:Loading libsecret
DEBUG:keyring.backend:Loading macOS
Google Password:
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.google.com:443
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /o/saml2/initsso?idpid=C02dze44a&spid=973789566129&forceauthn=false HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /ServiceLogin?passive=1xxxxxx&continue=https://accounts.google.com/o/saml2/initsso?idpid%3xxxxxx%26spid%3xxxxxxxxxx%26forceauthn%3Dfalse%26from_login%3Dxxxxxxxxxxxxxxxxxx&followup=https://accounts.google.com/o/saml2/initsso?idpid%3xxxxxxxxxxxxxforceauthn%3Dfalse%26from_login%3xxxxxxxxxxxxxxxxxxxxx=popup&oauth=1&faa=1&sarp=1&scc=1 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /signin/v1/lookup HTTP/1.1" 302 242
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /signin/rejected?rrk=88&hl=ru HTTP/1.1" 200 None
INFO:root:Handling new-style login page
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aws_google_auth/__init__.py", line 79, in cli
    process_auth(args, config)
  File "/usr/local/lib/python3.6/site-packages/aws_google_auth/__init__.py", line 243, in process_auth
    google_client.do_login()
  File "/usr/local/lib/python3.6/site-packages/aws_google_auth/google.py", line 256, in do_login
    passwd_challenge_url = 'https://accounts.google.com' + form.get('action')
AttributeError: 'NoneType' object has no attribute 'get'`

I`ve tried with deferent OS: 
1. CentOS v8; Python 3.6.8; pip 21.3.1; aws-google-auth 0.0.37; aws-cli/2.5.4
2. "Debian GNU/Linux 11; Python 3.9.2; pip 22.0.4; aws-google-auth 0.0.37; aws-cli/2.5.4

The same result 1:1

**Comment by myl82** [comment] 2022-04-13 07:39
Is there any solution, how to resolve this it?
The same issue:

aws-google-auth -I ******* -S xxxxxxx -d 28800 -p lmg -R ****** [-uuser@email.com](mailto:-uuser@email.com) -k -l debug

```
INFO:root:aws_google_auth: SAML cache not found
DEBUG:keyring.backend:Loading Gnome
DEBUG:keyring.backend:Loading Google
DEBUG:keyring.backend:Loading Windows (alt)
DEBUG:keyring.backend:Loading file
DEBUG:keyring.backend:Loading keyczar
DEBUG:keyring.backend:Loading multi
DEBUG:keyring.backend:Loading pyfs
DEBUG:keyring.backend:Loading KWallet
DEBUG:keyring.backend:Loading SecretService
DEBUG:keyring.backend:Loading Windows
DEBUG:keyring.backend:Loading chainer
DEBUG:keyring.backend:Loading libsecret
DEBUG:keyring.backend:Loading macOS
Google Password:
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.google.com:443
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /o/saml2/initsso?idpid=Cxxxxxxx&spid=9xxxxxxxxx&forceauthn=false HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /ServiceLogin?passive=1xxxxxx&continue=https://accounts.google.com/o/saml2/initsso?idpid%3xxxxxx%26spid%3xxxxxxxxxx%26forceauthn%3Dfalse%26from_login%3Dxxxxxxxxxxxxxxxxxx&followup=https://accounts.google.com/o/saml2/initsso?idpid%3xxxxxxxxxxxxxforceauthn%3Dfalse%26from_login%3xxxxxxxxxxxxxxxxxxxxx=popup&oauth=1&faa=1&sarp=1&scc=1 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /signin/v1/lookup HTTP/1.1" 302 242
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /signin/rejected?rrk=88&hl=ru HTTP/1.1" 200 None
INFO:root:Handling new-style login page
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aws_google_auth/__init__.py", line 79, in cli
    process_auth(args, config)
  File "/usr/local/lib/python3.6/site-packages/aws_google_auth/__init__.py", line 243, in process_auth
    google_client.do_login()
  File "/usr/local/lib/python3.6/site-packages/aws_google_auth/google.py", line 256, in do_login
    passwd_challenge_url = 'https://accounts.google.com' + form.get('action')
AttributeError: 'NoneType' object has no attribute 'get'
```

I`ve tried with deferent OS:

CentOS v8; Python 3.6.8; pip 21.3.1; aws-google-auth 0.0.37; aws-cli/2.5.4
"Debian GNU/Linux 11; Python 3.9.2; pip 22.0.4; aws-google-auth 0.0.37; aws-cli/2.5.4
The same result 1:1

**Comment by simonexmachina** [comment] 2022-08-08 05:07
I'm seeing the same problem

**Comment by axel-gonzalez-121** [comment] 2022-09-15 17:47
Same problem for me, version 0.0.38

**Comment by kriation** [comment] 2022-09-15 18:26
@axel-gonzalez-121 could you share a stack trace of the error when it occurs?

**Comment by axel-gonzalez-121** [comment] 2022-09-15 18:41
@kriation sure, im just loggin using $ aws-google-auth on my console (Windows CMD console) and this is what i got after fill all the steps (username, idp, sp, password) 

![image](https://user-images.githubusercontent.com/66963517/190484044-a58d5e3d-ea2a-40d0-ada7-c5758ebd926d.png)

**Comment by kriation** [comment] 2022-09-15 18:58
Thanks @axel-gonzalez-121.
Could you run through it again, passing --save-failure-html and --save-saml-flow?

The first will save any failures to saml.html in the local directory. The second will generate a directory with multiple files that include the GET and POST responses in each step of the flow.

Once generated, attach them to this issue.

**Comment by axel-gonzalez-121** [comment] 2022-09-15 19:39
@kriation Where should that files and folder be created? I have run the command with that two flags and check into C:\Python310\lib\site-packages\aws_google_auth and i can't found it . Also i checked in the route that i have open my console, can't found it too 

![aws-google-auth-bug](https://user-images.githubusercontent.com/66963517/190494079-f009d6a3-f1b9-4917-b7f8-6f8ef2b59dfb.png)

**Comment by kriation** [comment] 2022-09-15 20:01
@axel-gonzalez-121, the generated content the local directory that you were in when you ran aws-google-auth.

**Comment by drover25** [comment] 2023-08-18 17:24
Tried running with --save-saml-flow

I get the following error from Google
<img width="596" alt="image" src="https://github.com/cevoaustralia/aws-google-auth/assets/9020172/adda068d-b1e7-40d3-a73f-79a23a9cd1f8">

**Comment by samitkap** [comment] 2024-05-02 21:08
Getting the same issue as others on version 0.0.38 
`AttributeError: 'NoneType' object has no attribute 'get'`

Eventually (if you're in luck) it works after about 20 minutes of inactivity.

**Comment by a-l3x** [comment] 2024-06-25 11:33
I am also having this issue on version 0.0.38 now and it doesn't go away, also --save-failure-html doesn't save a html:
```
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/aws_google_auth/__init__.py", line 79, in cli
    process_auth(args, config)
  File "/opt/homebrew/lib/python3.11/site-packages/aws_google_auth/__init__.py", line 243, in process_auth
    google_client.do_login()
  File "/opt/homebrew/lib/python3.11/site-packages/aws_google_auth/google.py", line 215, in do_login
    self.cont = first_page.find('input', {'name': 'continue'}).get('value')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```
