### ISSUE TITLE
ERROR:root:'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by kjoneandrei** [cevoaustralia/aws-google-auth#166] opened 2020-02-27 08:55 UTC
trying to use `aws-google-auth` at version `0.0.33` and get the following error: 

```
$ aws-google-auth  
Google Password: 
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-google-auth/0.0.33/libexec/lib/python3.7/site-packages/aws_google_auth/__init__.py", line 73, in cli
    process_auth(args, config)
  File "/usr/local/Cellar/aws-google-auth/0.0.33/libexec/lib/python3.7/site-packages/aws_google_auth/__init__.py", line 218, in process_auth
    google_client.do_login()
  File "/usr/local/Cellar/aws-google-auth/0.0.33/libexec/lib/python3.7/site-packages/aws_google_auth/google.py", line 228, in do_login
    'name': 'ProfileInformation'
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by ahilsend** [comment] 2020-02-27 08:57
Looks like a duplicate of https://github.com/cevoaustralia/aws-google-auth/issues/164 :upside_down_face:

**Comment by nonspecialist** [comment] 2020-02-27 09:16
Yep, dupe of #164

**Closed by nonspecialist** 2020-02-27 09:16 UTC
